### ISSUE TITLE
Daily objectives

### ISSUE THREAD

**Issue by PLTytus** [Senexis/RDO-GG-Tunables#3]
Result of `func_17047()` is current day of week by game point of view - and it is not the same as in-real. Of course, 0 means Sunday.

Due to this situation, Daily Objectives in Quick View section are in incorrect order.

```
int func_14046()//Position - 0x4989C6
{
	int iVar0;
	int iVar1;
	
	iVar0 = NETWORK::GET_CLOUD_TIME_AS_INT();
	iVar1 = (iVar0 - 1555999200);
	if (iVar1 < 0)
	{
		iVar1 = (iVar1 * -1);
	}
	iVar1 = (iVar1 / 86400);
	return iVar1;
}

int func_14047()//Position - 0x4989F5
{
	int iVar0;
	
	iVar0 = (func_14046() % 7);
	return iVar0;
}
```

```
0 = Tuesday
1 = Wednesday
2 = Thursday
3 = Friday
4 = Saturday
5 = Sunday
6 = Monday
```

**Comment by Senexis** [comment]
Thanks so much for letting me know! The change I just made should resolve this issue. Feel free to let me know anything else you might find, I really appreciate you taking the time to report this issue!
